apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8fbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8fbe
    app.kubernetes.io/part-of: integ-app-hvpb
  name: hacbs-test-project-8fbe
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8fbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8fbe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/integration1-izba-tenant/integ-app-hvpb/hacbs-test-project-8fbe@sha256:e57cd5ac56f3cf89a6e315d0d1fe2d54a3afcdeec17abb1b85716f7ea478171c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
